### PR TITLE
read description for full things

### PR DESCRIPTION
**Pull request by DaveFan19**
Added: knockout blue and green little shoots mechanic,

Fixed:bf's idle being too slow,and bf's color in knockout

### CODE REVIEW

**Comment by Pico8430** [comment]
Going to test this later, seems pretty dope.

**Comment by DaveFan19** [comment]
> Going to test this later, seems pretty dope.
> 
> 

thanks

**Comment by DaveFan19** [comment]
> Just noticed that you also added the bf spritesheet on Knockout and the attack things. This might be a good pull request after i finish testing.
> 
> While i test this later, could you check if there's something more that needs to be improved? Thanks. (also yes i'm working on the sans week somehow)

for now i just did the bf color because knockout's bf spritesheet is glitched. and the blue and green shoots are a just a bit glitched but aside from that its good

**Comment by Pico8430** [comment]
HOLY CRAP THIS WORKS AMAZING

**Pull request merged**
